// modules/messaging/message-types.js
/**
 * 메시지 타입 상수
 * @readonly
 * @enum {string}
 */
export const MessageTypes = {
  // 세그먼트 트리 업데이트
  UPDATE_SEGMENT_TREE: "UPDATE_SEGMENT_TREE",

  // NovelAI 프롬프트 업데이트
  UPDATE_NOVELAI_PROMPT: "UPDATE_NOVELAI_PROMPT",
  SET_POSITIVE_PROMPT: "SET_POSITIVE_PROMPT",
  SET_NEGATIVE_PROMPT: "SET_NEGATIVE_PROMPT",

  // 해상도 및 배치 설정
  UPDATE_RESOLUTION: "UPDATE_RESOLUTION",
  UPDATE_BATCH_SIZE: "UPDATE_BATCH_SIZE",

  // 이미지 생성 관련
  GENERATE_IMAGE: "GENERATE_IMAGE",
  START_AUTO_GENERATION: "START_AUTO_GENERATION",
  STOP_AUTO_GENERATION: "STOP_AUTO_GENERATION",
  GENERATION_COMPLETE: "GENERATION_COMPLETE",

  // NovelAI 인터페이스 상태
  NAI_INTERFACE_CHANGED: "NAI_INTERFACE_CHANGED",

  // 프리셋 및 와일드카드
  SAVE_PRESET: "SAVE_PRESET",
  LOAD_PRESET: "LOAD_PRESET",
  GET_PRESET_LIST: "GET_PRESET_LIST",
  GET_WILDCARD_VALUES: "GET_WILDCARD_VALUES",
};
